name: 'TrinityCoreGitHubActions-pr-labeler'
description: 'Pull Request labeler for TrinityCore repositorye'
author: 'TrinityCore'
inputs:
  token:
    description: 'GitHub token with access to the repository'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
