name: 'TrinityCoreGitHubActions-issue-closer'
description: 'Issue closer for TrinityCore repository'
author: 'TrinityCore'
inputs:
  token:
    description: 'GitHub token with access to the repository'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
